-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 10:04:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema thrift_bank_pemex
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `thrift_bank_pemex` ;
USE `thrift_bank_pemex` ;

-- -----------------------------------------------------
-- Table `thrift_bank_pemex`.`ui_role`
-- -----------------------------------------------------

CREATE TABLE thrift_bank_pemex.ui_role (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  created_at datetime NOT NULL,
  last_ts datetime NOT NULL,
  created_by varchar(50) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY constraint_role_name (name)
  ); 

-- -----------------------------------------------------
-- Table `thrift_bank_pemex`.`ui_module`
-- -----------------------------------------------------

CREATE TABLE thrift_bank_pemex.ui_module (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  created_at datetime NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY constraint_module_name(name)
); 

-- -----------------------------------------------------
-- Table `thrift_bank_pemex`.`ui_role_modules`
-- -----------------------------------------------------

  CREATE TABLE thrift_bank_pemex.ui_role_modules (
  id int(11) NOT NULL AUTO_INCREMENT,
  id_ui_role int(11) NOT NULL,
  id_ui_module int(11) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY constraint_role_module (id_ui_role,id_ui_module),
  FOREIGN KEY (id_ui_role) REFERENCES ui_role (id),
  FOREIGN KEY (id_ui_module) REFERENCES ui_module (id)
  ); 

-- -----------------------------------------------------
-- Table `thrift_bank_pemex`.`market`
-- -----------------------------------------------------

CREATE TABLE thrift_bank_pemex.user (
  id int(11) NOT NULL AUTO_INCREMENT,
  user_id varchar(50) NOT NULL,
  userName varchar(100) NOT NULL,
  password varchar(50)not null,
  created_at datetime NOT NULL,
  id_ui_role int(11) NOT NULL,
  last_update_ts datetime NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY constraint_user (userName),
  FOREIGN KEY (id_ui_role) REFERENCES ui_role (id)
  );

